Repository 100-hours-a-week/8-team-kar98-luckeat-be, pull requests merged in 2025-03, with the labels that each got.

#47 카테고리 관련 API MVC 작성
  src/main/java/com/luckeat/luckeatbackend/category/controller/CategoryController.java
Labels: 제안

#53 refactor: Remove Apply spotless in CI workflow
  .github/workflows/build-test.yml
Labels: 버그-일반

#57 54 feature add jwt and errorcode at category domain edwin
  src/main/java/com/luckeat/luckeatbackend/category/controller/CategoryController.java
  src/main/java/com/luckeat/luckeatbackend/category/repository/CategoryRepository.java
  src/main/java/com/luckeat/luckeatbackend/category/service/CategoryService.java
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
Labels: 제안

#56 chore(ci): prevent semantic-release from pushing to develop branch
  .releaserc.json
Labels: 버그-일반, semantic-release

#58 Update issue templates
  .github/ISSUE_TEMPLATE/refactoring-request.md
Labels: 제안

#61 리뷰 관련 예외 처리 개선 및 소프트 삭제 기능 추가
  src/main/java/com/luckeat/luckeatbackend/common/exception/review/ReviewNotFoundException.java
  src/main/java/com/luckeat/luckeatbackend/review/controller/ReviewController.java
  src/main/java/com/luckeat/luckeatbackend/review/dto/MessageResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewListResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/review/model/Review.java
  src/main/java/com/luckeat/luckeatbackend/review/repository/ReviewRepository.java
  src/main/java/com/luckeat/luckeatbackend/review/service/ReviewService.java
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
Labels: 제안

#67 59 refactoring errorcode structure refactoring
  .githooks/pre-commit
  src/main/java/com/luckeat/luckeatbackend/category/service/CategoryService.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/ErrorCode.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/ErrorResponse.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/base/BadRequestException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/base/ConflictException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/base/CustomException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/base/DatabaseErrorException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/base/ExternalApiException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/base/FileUploadException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/base/ForbiddenException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/base/InternalServerErrorException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/base/NotFoundException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/base/UnauthorizedException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/base/ValidationException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/category/CategoryInvalidImageException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/category/CategoryInvalidNameException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/category/CategoryNameDuplicateException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/category/CategoryNotFoundException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/permission/PermissionForbiddenException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/permission/PermissionInvalidRoleException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/permission/PermissionNotFoundException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/product/ProductForbiddenException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/product/ProductInvalidImageException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/product/ProductInvalidNameException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/product/ProductInvalidPriceException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/product/ProductNameDuplicateException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/product/ProductNotFoundException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/review/ReviewForbiddenException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/review/ReviewInvalidContentException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/review/ReviewInvalidImageException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/review/ReviewInvalidRatingException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/review/ReviewNotFoundException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/store/StoreForbiddenException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/store/StoreInvalidAddressException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/store/StoreInvalidBusinessHoursException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/store/StoreInvalidDescriptionException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/store/StoreInvalidPhoneNumberException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/store/StoreNotFoundException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/user/EmailDuplicateException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/user/NicknameDuplicateException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/user/UserInvalidEmailException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/user/UserInvalidNicknameException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/user/UserInvalidPasswordException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/user/UserNotFoundException.java
Labels: 제안

#65 refactor: checkstyle 관련 설정 제거
  .github/workflows/checkstyle.yml
  build.gradle
  checkstyle/naver-checkstyle-rules.xml
  checkstyle/naver-checkstyle-spotless.xml
  checkstyle/naver-checkstyle-suppressions.xml
  checkstyle/naver-intellij-formatter.xml
Labels: 제안

#71 카테고리
  src/main/java/com/luckeat/luckeatbackend/category/repository/CategoryRepository.java
  src/main/java/com/luckeat/luckeatbackend/category/service/CategoryService.java
Labels: 버그-심각

#78 리뷰 관련 예외 처리 개선
  src/main/java/com/luckeat/luckeatbackend/review/controller/ReviewController.java
  src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewUpdateDto.java
  src/main/java/com/luckeat/luckeatbackend/review/service/ReviewService.java
  src/main/java/com/luckeat/luckeatbackend/users/model/User.java
Labels: 제안

#81 feat : 리뷰 권한 관련 DTO 및 서비스, 컨트롤러 삭제 및 권한 중복 에러 코드 추가
  src/main/java/com/luckeat/luckeatbackend/common/exception/ErrorCode.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/permission/PermissionAlreadyExistsException.java
  src/main/java/com/luckeat/luckeatbackend/permission/controller/ReviewPermissionController.java
  src/main/java/com/luckeat/luckeatbackend/permission/dto/MessageResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/permission/dto/PermissionRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/permission/repository/ReviewPermissionRepository.java
  src/main/java/com/luckeat/luckeatbackend/permission/service/ReviewPermissionService.java
  src/main/java/com/luckeat/luckeatbackend/review/service/ReviewService.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/controller/ReviewPermissionController.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/dto/PermissionListResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/dto/PermissionRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/dto/PermissionResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/model/ReviewPermission.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/repository/ReviewPermissionRepository.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/service/ReviewPermissionService.java
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
Labels: 제안

#83 82 refactoring api 스웨거 구현 및 스프링 부트 버전 변경
  build.gradle
  src/main/java/com/luckeat/luckeatbackend/category/controller/CategoryController.java
  src/main/java/com/luckeat/luckeatbackend/category/model/Category.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/user/EmailDuplicateException.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/user/NicknameDuplicateException.java
  src/main/java/com/luckeat/luckeatbackend/config/SwaggerConfig.java
  src/main/java/com/luckeat/luckeatbackend/product/controller/ProductController.java
  src/main/java/com/luckeat/luckeatbackend/product/dto/ProductRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/product/dto/ProductResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/product/dto/ProductStatusRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/review/controller/ReviewController.java
  src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewListResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewUpdateDto.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/controller/ReviewPermissionController.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/dto/PermissionListResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/dto/PermissionRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/dto/PermissionResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/ProductResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreDetailResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/model/Store.java
  src/main/java/com/luckeat/luckeatbackend/users/controller/UserController.java
  src/main/java/com/luckeat/luckeatbackend/users/dto/LoginRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/users/dto/LoginResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/users/dto/NicknameUpdateDto.java
  src/main/java/com/luckeat/luckeatbackend/users/dto/PasswordUpdateDto.java
  src/main/java/com/luckeat/luckeatbackend/users/dto/RegisterRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/users/dto/UserInfoResponseDto.java
Labels: 제안

#85 feat: JWT 블랙리스트 기능 추가 및 로그아웃 API 구현
  build.gradle
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
  src/main/java/com/luckeat/luckeatbackend/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/luckeat/luckeatbackend/users/controller/UserController.java
  src/main/java/com/luckeat/luckeatbackend/users/model/JwtBlacklist.java
  src/main/java/com/luckeat/luckeatbackend/users/repository/JwtBlacklistRepository.java
  src/main/java/com/luckeat/luckeatbackend/users/service/JwtBlacklistService.java
  src/test/java/com/luckeat/luckeatbackend/LuckeatApplicationTests.java
Labels: 제안

#89 리뷰와 가게 간의 관계 설정 및 가게 상세 응답에 리뷰 목록 추가
  src/main/java/com/luckeat/luckeatbackend/review/model/Review.java
  src/main/java/com/luckeat/luckeatbackend/review/repository/ReviewRepository.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreDetailResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/model/Store.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 제안

#91 develop 브랜치에 push 됐을 때 EC2에 자동 배포되는 워크플로우 추가
  .github/workflows/develop-deploy.yml
Labels: 제안

#93 리뷰 생성 및 수정 시 가게 평균 평점 업데이트 기능 추가, 가게 테이블 평균 별점 컬럼 추가
  src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/review/service/ReviewService.java
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreDetailResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/model/Store.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 버그-일반, 제안

#96 모든 가게 응답 DTO에 리뷰 갯수 카운트 추가
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreResponseDto.java
Labels: 제안

#102 내 가게 정보 조회 API 추가 및 관련 DTO 수정
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/MyStoreResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreDetailResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/store/repository/StoreRepository.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 제안

#105 103 refactoring 백엔드 개발운영 환경 분리
  .github/workflows/build-test.yml
  .github/workflows/deploy.yml
  .github/workflows/develop-deploy.yml
  .github/workflows/main-deploy.yml
Labels: 제안

#104 db 수정 사항
  src/main/java/com/luckeat/luckeatbackend/category/controller/CategoryController.java
  src/main/java/com/luckeat/luckeatbackend/category/model/Category.java
  src/main/java/com/luckeat/luckeatbackend/category/repository/CategoryRepository.java
  src/main/java/com/luckeat/luckeatbackend/category/service/CategoryService.java
  src/main/java/com/luckeat/luckeatbackend/product/repository/ProductRepository.java
  src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java
  src/main/java/com/luckeat/luckeatbackend/review/service/ReviewService.java
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/MyStoreResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreDetailResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/model/Store.java
  src/main/java/com/luckeat/luckeatbackend/store/repository/StoreRepository.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
  src/main/java/com/luckeat/luckeatbackend/users/model/JwtBlacklist.java
  src/main/java/com/luckeat/luckeatbackend/users/service/JwtBlacklistService.java
  src/test/java/com/luckeat/luckeatbackend/category/controller/CategoryControllerTest.java
  src/test/java/com/luckeat/luckeatbackend/category/manual/CategoryManualTest.java
  src/test/java/com/luckeat/luckeatbackend/category/repository/CategoryRepositoryTest.java
  src/test/java/com/luckeat/luckeatbackend/category/service/CategoryServiceTest.java
Labels: 제안

#113 110 refactoring short url rediret 함수 반환값 수정
  src/main/java/com/luckeat/luckeatbackend/short_url/service/ShortUrlService.java
Labels: 제안

#114 chore: 가게 공유 횟수 증가 기능 및 관련 메서드 삭제
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 제안

#115 fix: semantic-release 설정에서 불필요한 npm 플러그인 제거
  .releaserc.json
Labels: 버그-일반

#116 StoreRequestDto에 리뷰 요약, 평균 별점, 구글 장소 ID 필드 추가 및 유효성 검사 수정
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreRequestDto.java
Labels: 버그-일반

#120 feat: ShortUrlController에 사용자 요청 정보 로깅 기능 추가 및 ShortUrlService의 반환 URL 수정
  src/main/java/com/luckeat/luckeatbackend/short_url/controller/ShortUrlController.java
  src/main/java/com/luckeat/luckeatbackend/short_url/service/ShortUrlService.java
Labels: 제안

#121 가게 정보 요청시 유효성 검사 수정
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 버그-일반

#125 fix: ShortUrlController의 경로 수정 및 ShortUrlService의 반환 URL 형식 변경
  src/main/java/com/luckeat/luckeatbackend/short_url/controller/ShortUrlController.java
  src/main/java/com/luckeat/luckeatbackend/short_url/service/ShortUrlService.java
Labels: 버그-심각

#130 Update ShortUrlService.java
  src/main/java/com/luckeat/luckeatbackend/short_url/service/ShortUrlService.java
Labels: 버그-심각

#131 Update SecurityConfig.java
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
Labels: 버그-심각

#132 Update SecurityConfig.java
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
Labels: 버그-심각

#133 securityConfig /s/** 경로 허용 수정
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
Labels: 버그-일반

#135 feat: image upload functionality, error handling, and AWS S3 configuration.
  .gitignore
  build.gradle
  src/main/java/com/luckeat/luckeatbackend/common/controller/ImageUploadController.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/ErrorResponse.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/luckeat/luckeatbackend/common/service/S3UploadService.java
  src/main/java/com/luckeat/luckeatbackend/config/AwsS3Config.java
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
  src/main/java/com/luckeat/luckeatbackend/short_url/controller/ShortUrlController.java
  src/main/java/com/luckeat/luckeatbackend/short_url/service/ShortUrlService.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 제안

#137 getAllProducts 메서드에서 삭제된 제품을 제외하도록 수정
  src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java
Labels: 버그-일반

#141 상품 관련 DTO 및 서비스 수정: 상품 수량 및 설명 필드 추가, 상품 상태 수정 메서드 이름 변경
  src/main/java/com/luckeat/luckeatbackend/product/controller/ProductController.java
  src/main/java/com/luckeat/luckeatbackend/product/dto/ProductCountRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/product/dto/ProductRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/product/dto/ProductResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/product/model/Product.java
  src/main/java/com/luckeat/luckeatbackend/product/repository/ProductRepository.java
  src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java
  src/main/java/com/luckeat/luckeatbackend/review/model/Review.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/ProductResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/model/Store.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 제안

#143 가게 DB 및 상품갯수 응답 DTO 수정
  src/main/java/com/luckeat/luckeatbackend/product/controller/ProductController.java
  src/main/java/com/luckeat/luckeatbackend/product/dto/ProductCountRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/ProductResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreDetailResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreResponseDto.java
Labels: 제안
