Repository 100-hours-a-week/8-team-kar98-luckeat-be, pull requests merged in 2025-04, with the labels that each got.

#146 리뷰 작성 권한 URL 필드 제거 및 관련 DTO 수정
  src/main/java/com/luckeat/luckeatbackend/store/dto/MyStoreResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreDetailResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/model/Store.java
Labels: 제안

#148 카테고리 API 접근 권한 수정 - GET 요청에 대해 모든 경로 허용
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
Labels: 버그-일반

#152 MyStoreResponseDto에 픽업 가능 시간 필드 추가
  src/main/java/com/luckeat/luckeatbackend/store/dto/MyStoreResponseDto.java
Labels: 버그-일반

#153 feat: isOpen 부활 및 예약DTO에 닉네임 추가
  src/main/java/com/luckeat/luckeatbackend/product/controller/ProductController.java
  src/main/java/com/luckeat/luckeatbackend/product/dto/ProductResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/product/model/Product.java
  src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java
  src/main/java/com/luckeat/luckeatbackend/reservation/dto/ReservationResponseDto.java
Labels: 제안

#155 ProductRequestDto에 상품 판매 여부(isOpen) 필드 추가
  src/main/java/com/luckeat/luckeatbackend/product/dto/ProductRequestDto.java
Labels: 버그-일반

#157 가게의 상품 중 판매 중인 상품 존재 여부 확인 기능 수정
  src/main/java/com/luckeat/luckeatbackend/product/repository/ProductRepository.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 버그-일반

#159 Spring Boot Actuator 의존성 추가 및 API 접근 권한 설정
  build.gradle
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
Labels: 제안

#160 헬스체크 api 추가
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
Labels: 버그-일반, 제안

#164 재고 관리 기능 추가 및 예외 처리 개선
  src/main/java/com/luckeat/luckeatbackend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/luckeat/luckeatbackend/product/model/Product.java
  src/main/java/com/luckeat/luckeatbackend/reservation/controller/ReservationController.java
  src/main/java/com/luckeat/luckeatbackend/reservation/service/ReservationService.java
  src/main/java/com/luckeat/luckeatbackend/users/dto/UserInfoResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/users/model/User.java
Labels: 제안

#166 가게에 이미 등록된 상품 존재 여부 확인 기능 추가
  src/main/java/com/luckeat/luckeatbackend/product/repository/ProductRepository.java
  src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java
Labels: 제안

#168 상품 생성 및 업데이트 메서드 이름 변경, 상품 업데이트 로직 추가
  src/main/java/com/luckeat/luckeatbackend/product/controller/ProductController.java
  src/main/java/com/luckeat/luckeatbackend/product/dto/ProductRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java
Labels: 버그-일반

#170 User 모델의 totalSavedMoney 및 totalProductCount 필드 초기값 설정
  src/main/java/com/luckeat/luckeatbackend/users/model/User.java
Labels: 버그-일반

#172 럭키트 예약 완료후 재고가 0개이면 상품 isopen false로 처리하기
  src/main/java/com/luckeat/luckeatbackend/product/model/Product.java
  src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java
Labels: 버그-일반

#174 예약 취소 후 재고가 0이상 일때 상품의 isOpen 상태를 true로 변경하는 로직 추가
  src/main/java/com/luckeat/luckeatbackend/reservation/service/ReservationService.java
Labels: 버그-일반

#176 175 devops 백엔드 모니터링 설정하기
  .github/workflows/build-test.yml
  .github/workflows/deploy.yml
  .gitignore
  build.gradle
Labels: 제안

#181 build: Bucket4j 라이브러리 추가 및 버전 업데이트
  .github/workflows/deploy.yml
  build.gradle
Labels: 제안

#184 예약 관련 DTO 및 서비스에서 리뷰 작성 여부 필드를 삭제하고, 관련 로직을 제거함
  src/main/java/com/luckeat/luckeatbackend/reservation/dto/ReservationResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/reservation/model/Reservation.java
  src/main/java/com/luckeat/luckeatbackend/reservation/service/ReservationService.java
  src/main/java/com/luckeat/luckeatbackend/review/service/ReviewService.java
Labels: 버그-심각

#180 ci: deploy 워크플로우에 Sentry 릴리즈 설정 추가
  .github/workflows/build-test.yml
  .github/workflows/deploy.yml
Labels: 버그-심각

#187 예약 ID를 필수 필드로 추가하고, 리뷰 작성 시 예약 확인 로직을 개선하여 예약의 소유자 및 상태를 검증하도록 수정함
  src/main/java/com/luckeat/luckeatbackend/reservation/service/ReservationService.java
  src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/review/model/Review.java
  src/main/java/com/luckeat/luckeatbackend/review/repository/ReviewRepository.java
  src/main/java/com/luckeat/luckeatbackend/review/service/ReviewService.java
Labels: 버그-일반, 제안

#193 회원가입 로직 개선 및 상품 재고에 비관적락 적용
  src/main/java/com/luckeat/luckeatbackend/product/model/Product.java
  src/main/java/com/luckeat/luckeatbackend/product/repository/ProductRepository.java
  src/main/java/com/luckeat/luckeatbackend/reservation/service/ReservationService.java
  src/main/java/com/luckeat/luckeatbackend/users/service/UserService.java
Labels: 버그-일반, 제안

#197 API Rate Limit 기능 추가 및 관련 문서 작성
  RATE_LIMIT_README.md
  build.gradle
  src/main/java/com/luckeat/luckeatbackend/LuckeatApplication.java
  src/main/java/com/luckeat/luckeatbackend/common/filter/IpAttributeFilter.java
  src/main/java/com/luckeat/luckeatbackend/common/filter/RateLimitFilter.java
  src/main/java/com/luckeat/luckeatbackend/config/RateLimitConfig.java
  src/main/java/com/luckeat/luckeatbackend/config/WebConfig.java
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
  test-rate-limit.sh
Labels: 제안

#196 상품 재고 감소 로직을 개선
  src/main/java/com/luckeat/luckeatbackend/product/repository/ProductRepository.java
  src/main/java/com/luckeat/luckeatbackend/reservation/service/ReservationService.java
Labels: 버그-일반

#199 메인 클래스 지정 및 로그 디렉토리 생성 기능 추가
  build.gradle
  src/main/java/com/luckeat/luckeatbackend/LuckeatApplication.java
  src/main/java/com/luckeat/luckeatbackend/common/filter/RequestLoggingFilter.java
  src/main/java/com/luckeat/luckeatbackend/config/WebConfig.java
  src/main/resources/logback-spring.xml
Labels: 제안

#201 로그 개선 및 CORS 설정 업데이트
  src/main/java/com/luckeat/luckeatbackend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/base/CustomException.java
  src/main/java/com/luckeat/luckeatbackend/config/WebConfig.java
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
Labels: 버그-심각

#203 focusing on workflow improvements, logging enhancements, and the implementation of API rate limiting
  .github/workflows/build-test.yml
  .github/workflows/deploy.yml
  .gitignore
  RATE_LIMIT_README.md
  build.gradle
  src/main/java/com/luckeat/luckeatbackend/LuckeatApplication.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/luckeat/luckeatbackend/common/exception/base/CustomException.java
  src/main/java/com/luckeat/luckeatbackend/common/filter/IpAttributeFilter.java
  src/main/java/com/luckeat/luckeatbackend/common/filter/RateLimitFilter.java
  src/main/java/com/luckeat/luckeatbackend/common/filter/RequestLoggingFilter.java
  src/main/java/com/luckeat/luckeatbackend/config/RateLimitConfig.java
  src/main/java/com/luckeat/luckeatbackend/config/WebConfig.java
  src/main/java/com/luckeat/luckeatbackend/product/controller/ProductController.java
  src/main/java/com/luckeat/luckeatbackend/product/dto/ProductRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/product/model/Product.java
  src/main/java/com/luckeat/luckeatbackend/product/repository/ProductRepository.java
  src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java
  src/main/java/com/luckeat/luckeatbackend/reservation/controller/ReservationController.java
  src/main/java/com/luckeat/luckeatbackend/reservation/dto/ReservationRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/reservation/dto/ReservationResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/reservation/model/Reservation.java
  src/main/java/com/luckeat/luckeatbackend/reservation/service/ReservationService.java
  src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/review/dto/ReviewResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/review/model/Review.java
  src/main/java/com/luckeat/luckeatbackend/review/repository/ReviewRepository.java
  src/main/java/com/luckeat/luckeatbackend/review/service/ReviewService.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/controller/ReviewPermissionController.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/dto/PermissionListResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/dto/PermissionRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/dto/PermissionResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/model/ReviewPermission.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/repository/ReviewPermissionRepository.java
  src/main/java/com/luckeat/luckeatbackend/reviewpermission/service/ReviewPermissionService.java
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
  src/main/java/com/luckeat/luckeatbackend/users/dto/UserInfoResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/users/model/User.java
  src/main/java/com/luckeat/luckeatbackend/users/service/UserService.java
  src/main/resources/logback-spring.xml
  test-rate-limit.sh
Labels: 제안

#204 feat: 비밀번호 필드의 설명을 Base64로 인코딩된 비밀번호로 수정, 소문자로 변환하여 검증하도록 수정
  src/main/java/com/luckeat/luckeatbackend/users/dto/LoginRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/users/dto/RegisterRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/users/service/UserService.java
Labels: 제안

#206 feat: 가게 목록 조회 API에 페이지네이션 기능 추가
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
  src/main/java/com/luckeat/luckeatbackend/store/repository/StoreRepository.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 제안

#207 출시를 위한 메인 머지
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
  src/main/java/com/luckeat/luckeatbackend/store/repository/StoreRepository.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
  src/main/java/com/luckeat/luckeatbackend/users/dto/LoginRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/users/dto/RegisterRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/users/service/UserService.java
Labels: 제안

#209 feat(store): 가게 목록 조회 API에 카테고리 필터링 및 위치 기반 검색 기능 추가
  src/main/java/com/luckeat/luckeatbackend/category/repository/CategoryRepository.java
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
  src/main/java/com/luckeat/luckeatbackend/store/model/Store.java
  src/main/java/com/luckeat/luckeatbackend/store/repository/StoreRepository.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 버그-심각

#210 출시를 위한 메인 머지
  src/main/java/com/luckeat/luckeatbackend/category/repository/CategoryRepository.java
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
  src/main/java/com/luckeat/luckeatbackend/store/model/Store.java
  src/main/java/com/luckeat/luckeatbackend/store/repository/StoreRepository.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 제안

#217 feat: 가게 목록 조회 API의 정렬 기준 및 쿼리 개선
  src/main/java/com/luckeat/luckeatbackend/store/repository/StoreRepository.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 버그-심각

#222 사용자 등록 요청 DTO에서 역할 필드를 문자열로 변경하고, 유효성 검사를 강화함.
  src/main/java/com/luckeat/luckeatbackend/users/dto/RegisterRequestDto.java
  src/main/java/com/luckeat/luckeatbackend/users/service/UserService.java
Labels: 제안

#225 제품 재고 감소 쿼리 수정 - 제품 수량이 정확히 일치할 때 is_open 필드 업데이트 로직 변경
  src/main/java/com/luckeat/luckeatbackend/product/repository/ProductRepository.java
Labels: 버그-일반

#228 PasswordUpdateDto에서 현재 비밀번호의 패턴 검사를 제거함
  src/main/java/com/luckeat/luckeatbackend/users/dto/PasswordUpdateDto.java
Labels: 버그-일반

#230 dockerfile, deploy.yml 수정
  .github/workflows/deploy.yml
  Dockerfile
Labels: 제안

#232 deploy 수정
  .github/workflows/deploy.yml
Labels: 버그-일반

#233 deploy.yml에서 AWS_REGION_SECRET 환경 변수 설정 위치 수정
  .github/workflows/deploy.yml
Labels: 버그-일반

#237 feat: Prometheus 및 Grafana 모니터링 시스템 설정 추가
  PROMETHEUS_GRAFANA_README.md
  build.gradle
  grafana/dashboards/loki-logs-dashboard.json
  grafana/dashboards/mysql-overview-dashboard.json
  grafana/provisioning/dashboards/dashboard.yml
  grafana/provisioning/datasources/datasource.yml
  loki-config.yml
  prometheus.yml
  promtail-config.yml
  src/main/java/com/luckeat/luckeatbackend/common/controller/MetricsTestController.java
  src/main/java/com/luckeat/luckeatbackend/common/interceptor/MetricsInterceptor.java
  src/main/java/com/luckeat/luckeatbackend/config/MetricsConfig.java
  src/main/java/com/luckeat/luckeatbackend/config/WebConfig.java
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
Labels: 제안

#245 feat: 가게, 리뷰 이미지 업로드를 위한 프리사인드 URL 구현
  src/main/java/com/luckeat/luckeatbackend/common/controller/ImageUploadController.java
  src/main/java/com/luckeat/luckeatbackend/common/dto/PresignedUrlResponse.java
  src/main/java/com/luckeat/luckeatbackend/common/service/S3UploadService.java
Labels: 제안

#252 Deploy-prod수정 main 머지
  .github/workflows/deploy-prod.yml
Labels: 제안

#256 feat: ALB, ASG를 이용한 무중단 배포 구현
  .github/workflows/deploy-prod.yml
Labels: 제안

#266 feat(store): 가게 목록 조회 성능 테스트 기능 추가 및 쿼리 실행 시간 측정 로직 개선
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 제안

#267 feat(cache): Redis 캐시 설정 및 가게 서비스에 캐시 적용
  build.gradle
  src/main/java/com/luckeat/luckeatbackend/config/CacheConfig.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 제안

#268 refactor(cache): Redis 캐시 설정에서 불필요한 타입 검증 제거
  src/main/java/com/luckeat/luckeatbackend/config/CacheConfig.java
Labels: 버그-심각

#269 feat(store): 가게 목록 조회 및 정렬 기능 개선
  src/main/java/com/luckeat/luckeatbackend/common/entity/BaseEntity.java
  src/main/java/com/luckeat/luckeatbackend/common/util/SortUtil.java
  src/main/java/com/luckeat/luckeatbackend/config/CacheConfig.java
  src/main/java/com/luckeat/luckeatbackend/review/repository/ReviewRepository.java
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreListDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreQueryResult.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/model/Store.java
  src/main/java/com/luckeat/luckeatbackend/store/repository/StoreRepository.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 제안

#271 feat(store) redis를 추가하여 랜딩페이지의 속도 향상
  build.gradle
  src/main/java/com/luckeat/luckeatbackend/common/entity/BaseEntity.java
  src/main/java/com/luckeat/luckeatbackend/common/util/SortUtil.java
  src/main/java/com/luckeat/luckeatbackend/config/CacheConfig.java
  src/main/java/com/luckeat/luckeatbackend/product/controller/ProductController.java
  src/main/java/com/luckeat/luckeatbackend/product/service/ProductService.java
  src/main/java/com/luckeat/luckeatbackend/review/repository/ReviewRepository.java
  src/main/java/com/luckeat/luckeatbackend/short_url/controller/ShortUrlController.java
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreListDto.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreQueryResult.java
  src/main/java/com/luckeat/luckeatbackend/store/dto/StoreResponseDto.java
  src/main/java/com/luckeat/luckeatbackend/store/model/Store.java
  src/main/java/com/luckeat/luckeatbackend/store/repository/StoreRepository.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 제안

#272 fix(StoreController): `/performance-test` 엔드포인트 매핑 오류 수정
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
Labels: 버그-심각

#273 fix(StoreController): Update performance test endpoint mapping
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
Labels: 버그-심각

#274 fix(StoreController): Update performance test endpoint mapping
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
Labels: 버그-심각

#275 fix(StoreController): Update performance test
  src/main/java/com/luckeat/luckeatbackend/security/SecurityConfig.java
  src/main/java/com/luckeat/luckeatbackend/store/controller/StoreController.java
  src/main/java/com/luckeat/luckeatbackend/store/service/StoreService.java
Labels: 버그-심각
